/*
 * generated by Xtext 2.36.0
 */
package org.example.evms.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.example.evms.evms.Evenement;
import org.example.evms.evms.EvmsPackage;
import org.example.evms.evms.Inscription;
import org.example.evms.evms.Lieu;
import org.example.evms.evms.Model;
import org.example.evms.evms.Notification;
import org.example.evms.evms.Utilisateur;
import org.example.evms.services.EvmsGrammarAccess;

@SuppressWarnings("all")
public class EvmsSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private EvmsGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == EvmsPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case EvmsPackage.EVENEMENT:
				sequence_Evenement(context, (Evenement) semanticObject); 
				return; 
			case EvmsPackage.INSCRIPTION:
				sequence_Inscription(context, (Inscription) semanticObject); 
				return; 
			case EvmsPackage.LIEU:
				sequence_Lieu(context, (Lieu) semanticObject); 
				return; 
			case EvmsPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case EvmsPackage.NOTIFICATION:
				sequence_Notification(context, (Notification) semanticObject); 
				return; 
			case EvmsPackage.UTILISATEUR:
				sequence_Utilisateur(context, (Utilisateur) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     RootElement returns Evenement
	 *     Evenement returns Evenement
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         titre=STRING? 
	 *         description=STRING? 
	 *         dateDebut=DATE? 
	 *         dateFin=DATE? 
	 *         lieu=[Lieu|ID] 
	 *         createur=[Utilisateur|ID] 
	 *         inscriptions+=Inscription* 
	 *         notifications+=Notification*
	 *     )
	 * </pre>
	 */
	protected void sequence_Evenement(ISerializationContext context, Evenement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     RootElement returns Inscription
	 *     Inscription returns Inscription
	 *
	 * Constraint:
	 *     (utilisateur=[Utilisateur|ID] evenement=[Evenement|ID])
	 * </pre>
	 */
	protected void sequence_Inscription(ISerializationContext context, Inscription semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, EvmsPackage.Literals.INSCRIPTION__UTILISATEUR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, EvmsPackage.Literals.INSCRIPTION__UTILISATEUR));
			if (transientValues.isValueTransient(semanticObject, EvmsPackage.Literals.INSCRIPTION__EVENEMENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, EvmsPackage.Literals.INSCRIPTION__EVENEMENT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getInscriptionAccess().getUtilisateurUtilisateurIDTerminalRuleCall_3_0_1(), semanticObject.eGet(EvmsPackage.Literals.INSCRIPTION__UTILISATEUR, false));
		feeder.accept(grammarAccess.getInscriptionAccess().getEvenementEvenementIDTerminalRuleCall_5_0_1(), semanticObject.eGet(EvmsPackage.Literals.INSCRIPTION__EVENEMENT, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     RootElement returns Lieu
	 *     Lieu returns Lieu
	 *
	 * Constraint:
	 *     (name=ID nom=STRING adresse=STRING? capacite=INT?)
	 * </pre>
	 */
	protected void sequence_Lieu(ISerializationContext context, Lieu semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     elements+=RootElement+
	 * </pre>
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     RootElement returns Notification
	 *     Notification returns Notification
	 *
	 * Constraint:
	 *     (message=STRING destinataire=[Utilisateur|ID] evenement=[Evenement|ID])
	 * </pre>
	 */
	protected void sequence_Notification(ISerializationContext context, Notification semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, EvmsPackage.Literals.NOTIFICATION__MESSAGE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, EvmsPackage.Literals.NOTIFICATION__MESSAGE));
			if (transientValues.isValueTransient(semanticObject, EvmsPackage.Literals.NOTIFICATION__DESTINATAIRE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, EvmsPackage.Literals.NOTIFICATION__DESTINATAIRE));
			if (transientValues.isValueTransient(semanticObject, EvmsPackage.Literals.NOTIFICATION__EVENEMENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, EvmsPackage.Literals.NOTIFICATION__EVENEMENT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getNotificationAccess().getMessageSTRINGTerminalRuleCall_3_0(), semanticObject.getMessage());
		feeder.accept(grammarAccess.getNotificationAccess().getDestinataireUtilisateurIDTerminalRuleCall_5_0_1(), semanticObject.eGet(EvmsPackage.Literals.NOTIFICATION__DESTINATAIRE, false));
		feeder.accept(grammarAccess.getNotificationAccess().getEvenementEvenementIDTerminalRuleCall_7_0_1(), semanticObject.eGet(EvmsPackage.Literals.NOTIFICATION__EVENEMENT, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     RootElement returns Utilisateur
	 *     Utilisateur returns Utilisateur
	 *
	 * Constraint:
	 *     (name=ID nom=STRING email=STRING (role='organisateur' | role='participant' | role='admin')? motDePasse=STRING?)
	 * </pre>
	 */
	protected void sequence_Utilisateur(ISerializationContext context, Utilisateur semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
