/*
 * generated by Xtext 2.36.0
 */
package org.example.evms.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.example.evms.services.EvmsGrammarAccess;

@SuppressWarnings("all")
public class EvmsSyntacticSequencer extends AbstractSyntacticSequencer {

	protected EvmsGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Evenement___InscriptionsKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q;
	protected AbstractElementAlias match_Evenement___NotificationsKeyword_12_0_LeftCurlyBracketKeyword_12_1_RightCurlyBracketKeyword_12_3__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (EvmsGrammarAccess) access;
		match_Evenement___InscriptionsKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEvenementAccess().getInscriptionsKeyword_11_0()), new TokenAlias(false, false, grammarAccess.getEvenementAccess().getLeftCurlyBracketKeyword_11_1()), new TokenAlias(false, false, grammarAccess.getEvenementAccess().getRightCurlyBracketKeyword_11_3()));
		match_Evenement___NotificationsKeyword_12_0_LeftCurlyBracketKeyword_12_1_RightCurlyBracketKeyword_12_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEvenementAccess().getNotificationsKeyword_12_0()), new TokenAlias(false, false, grammarAccess.getEvenementAccess().getLeftCurlyBracketKeyword_12_1()), new TokenAlias(false, false, grammarAccess.getEvenementAccess().getRightCurlyBracketKeyword_12_3()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Evenement___InscriptionsKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q.equals(syntax))
				emit_Evenement___InscriptionsKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Evenement___NotificationsKeyword_12_0_LeftCurlyBracketKeyword_12_1_RightCurlyBracketKeyword_12_3__q.equals(syntax))
				emit_Evenement___NotificationsKeyword_12_0_LeftCurlyBracketKeyword_12_1_RightCurlyBracketKeyword_12_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('inscriptions' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     createur=[Utilisateur|ID] (ambiguity) 'notifications' '{' notifications+=Notification
	 *     createur=[Utilisateur|ID] (ambiguity) ('notifications' '{' '}')? '}' (rule end)
	 
	 * </pre>
	 */
	protected void emit_Evenement___InscriptionsKeyword_11_0_LeftCurlyBracketKeyword_11_1_RightCurlyBracketKeyword_11_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('notifications' '{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     createur=[Utilisateur|ID] ('inscriptions' '{' '}')? (ambiguity) '}' (rule end)
	 *     inscriptions+=Inscription '}' (ambiguity) '}' (rule end)
	 
	 * </pre>
	 */
	protected void emit_Evenement___NotificationsKeyword_12_0_LeftCurlyBracketKeyword_12_1_RightCurlyBracketKeyword_12_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
