/*
 * generated by Xtext 2.36.0
 */
package org.example.evms.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.exampleevms.entity.ui.internal.EntityActivator;

public class EvmsUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EntityActivator.getInstance().getInjector("org.example.evms.Evms");
	}

}
