/*
 * generated by Xtext 2.36.0
 */
package org.example.evms.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.exampleevms.entity.ui.internal.EntityActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EvmsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(EntityActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		EntityActivator activator = EntityActivator.getInstance();
		return activator != null ? activator.getInjector(EntityActivator.ORG_EXAMPLE_EVMS_EVMS) : null;
	}

}
