/*
 * generated by Xtext 2.36.0
 */
package org.example.evms.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEvmsScopeProvider extends DelegatingScopeProvider {
}
