/*
 * generated by Xtext 2.36.0
 */
package org.example.evms.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class EvmsGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.evms.Evms.Model");
		private final Assignment cElementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cElementsRootElementParserRuleCall_0 = (RuleCall)cElementsAssignment.eContents().get(0);
		
		//Model:
		//    (elements+=RootElement)*;
		@Override public ParserRule getRule() { return rule; }
		
		//(elements+=RootElement)*
		public Assignment getElementsAssignment() { return cElementsAssignment; }
		
		//RootElement
		public RuleCall getElementsRootElementParserRuleCall_0() { return cElementsRootElementParserRuleCall_0; }
	}
	public class RootElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.evms.Evms.RootElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cEvenementParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cLieuParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cUtilisateurParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cInscriptionParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cNotificationParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//RootElement:
		//      Evenement
		//    | Lieu
		//    | Utilisateur
		//    | Inscription
		//    | Notification;
		@Override public ParserRule getRule() { return rule; }
		
		//  Evenement
		//| Lieu
		//| Utilisateur
		//| Inscription
		//| Notification
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Evenement
		public RuleCall getEvenementParserRuleCall_0() { return cEvenementParserRuleCall_0; }
		
		//Lieu
		public RuleCall getLieuParserRuleCall_1() { return cLieuParserRuleCall_1; }
		
		//Utilisateur
		public RuleCall getUtilisateurParserRuleCall_2() { return cUtilisateurParserRuleCall_2; }
		
		//Inscription
		public RuleCall getInscriptionParserRuleCall_3() { return cInscriptionParserRuleCall_3; }
		
		//Notification
		public RuleCall getNotificationParserRuleCall_4() { return cNotificationParserRuleCall_4; }
	}
	public class EvenementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.evms.Evms.Evenement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEvenementKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTitreKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTitreAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTitreSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cTitreAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDebutKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDateDebutAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDateDebutDATETerminalRuleCall_5_1_0 = (RuleCall)cDateDebutAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cFinKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDateFinAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDateFinDATETerminalRuleCall_6_1_0 = (RuleCall)cDateFinAssignment_6_1.eContents().get(0);
		private final Keyword cLieuKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cLieuAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cLieuLieuCrossReference_8_0 = (CrossReference)cLieuAssignment_8.eContents().get(0);
		private final RuleCall cLieuLieuIDTerminalRuleCall_8_0_1 = (RuleCall)cLieuLieuCrossReference_8_0.eContents().get(1);
		private final Keyword cOrganisateurKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cCreateurAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final CrossReference cCreateurUtilisateurCrossReference_10_0 = (CrossReference)cCreateurAssignment_10.eContents().get(0);
		private final RuleCall cCreateurUtilisateurIDTerminalRuleCall_10_0_1 = (RuleCall)cCreateurUtilisateurCrossReference_10_0.eContents().get(1);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cInscriptionsKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Assignment cInscriptionsAssignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final RuleCall cInscriptionsInscriptionParserRuleCall_11_2_0 = (RuleCall)cInscriptionsAssignment_11_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11_3 = (Keyword)cGroup_11.eContents().get(3);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cNotificationsKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Assignment cNotificationsAssignment_12_2 = (Assignment)cGroup_12.eContents().get(2);
		private final RuleCall cNotificationsNotificationParserRuleCall_12_2_0 = (RuleCall)cNotificationsAssignment_12_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12_3 = (Keyword)cGroup_12.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//// ====================== Evenement ======================
		//Evenement:
		//    'evenement' name=ID '{'
		//        ('titre' titre=STRING)?
		//        ('description' description=STRING)?
		//        ('debut' dateDebut=DATE)?
		//        ('fin' dateFin=DATE)?
		//        'lieu' lieu=[Lieu]
		//        'organisateur' createur=[Utilisateur]
		//        ('inscriptions' '{' inscriptions+=Inscription* '}')?
		//        ('notifications' '{' notifications+=Notification* '}')?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'evenement' name=ID '{'
		//    ('titre' titre=STRING)?
		//    ('description' description=STRING)?
		//    ('debut' dateDebut=DATE)?
		//    ('fin' dateFin=DATE)?
		//    'lieu' lieu=[Lieu]
		//    'organisateur' createur=[Utilisateur]
		//    ('inscriptions' '{' inscriptions+=Inscription* '}')?
		//    ('notifications' '{' notifications+=Notification* '}')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'evenement'
		public Keyword getEvenementKeyword_0() { return cEvenementKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('titre' titre=STRING)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'titre'
		public Keyword getTitreKeyword_3_0() { return cTitreKeyword_3_0; }
		
		//titre=STRING
		public Assignment getTitreAssignment_3_1() { return cTitreAssignment_3_1; }
		
		//STRING
		public RuleCall getTitreSTRINGTerminalRuleCall_3_1_0() { return cTitreSTRINGTerminalRuleCall_3_1_0; }
		
		//('description' description=STRING)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=STRING
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_4_1_0() { return cDescriptionSTRINGTerminalRuleCall_4_1_0; }
		
		//('debut' dateDebut=DATE)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'debut'
		public Keyword getDebutKeyword_5_0() { return cDebutKeyword_5_0; }
		
		//dateDebut=DATE
		public Assignment getDateDebutAssignment_5_1() { return cDateDebutAssignment_5_1; }
		
		//DATE
		public RuleCall getDateDebutDATETerminalRuleCall_5_1_0() { return cDateDebutDATETerminalRuleCall_5_1_0; }
		
		//('fin' dateFin=DATE)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'fin'
		public Keyword getFinKeyword_6_0() { return cFinKeyword_6_0; }
		
		//dateFin=DATE
		public Assignment getDateFinAssignment_6_1() { return cDateFinAssignment_6_1; }
		
		//DATE
		public RuleCall getDateFinDATETerminalRuleCall_6_1_0() { return cDateFinDATETerminalRuleCall_6_1_0; }
		
		//'lieu'
		public Keyword getLieuKeyword_7() { return cLieuKeyword_7; }
		
		//lieu=[Lieu]
		public Assignment getLieuAssignment_8() { return cLieuAssignment_8; }
		
		//[Lieu]
		public CrossReference getLieuLieuCrossReference_8_0() { return cLieuLieuCrossReference_8_0; }
		
		//ID
		public RuleCall getLieuLieuIDTerminalRuleCall_8_0_1() { return cLieuLieuIDTerminalRuleCall_8_0_1; }
		
		//'organisateur'
		public Keyword getOrganisateurKeyword_9() { return cOrganisateurKeyword_9; }
		
		//createur=[Utilisateur]
		public Assignment getCreateurAssignment_10() { return cCreateurAssignment_10; }
		
		//[Utilisateur]
		public CrossReference getCreateurUtilisateurCrossReference_10_0() { return cCreateurUtilisateurCrossReference_10_0; }
		
		//ID
		public RuleCall getCreateurUtilisateurIDTerminalRuleCall_10_0_1() { return cCreateurUtilisateurIDTerminalRuleCall_10_0_1; }
		
		//('inscriptions' '{' inscriptions+=Inscription* '}')?
		public Group getGroup_11() { return cGroup_11; }
		
		//'inscriptions'
		public Keyword getInscriptionsKeyword_11_0() { return cInscriptionsKeyword_11_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_11_1() { return cLeftCurlyBracketKeyword_11_1; }
		
		//inscriptions+=Inscription*
		public Assignment getInscriptionsAssignment_11_2() { return cInscriptionsAssignment_11_2; }
		
		//Inscription
		public RuleCall getInscriptionsInscriptionParserRuleCall_11_2_0() { return cInscriptionsInscriptionParserRuleCall_11_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11_3() { return cRightCurlyBracketKeyword_11_3; }
		
		//('notifications' '{' notifications+=Notification* '}')?
		public Group getGroup_12() { return cGroup_12; }
		
		//'notifications'
		public Keyword getNotificationsKeyword_12_0() { return cNotificationsKeyword_12_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_12_1() { return cLeftCurlyBracketKeyword_12_1; }
		
		//notifications+=Notification*
		public Assignment getNotificationsAssignment_12_2() { return cNotificationsAssignment_12_2; }
		
		//Notification
		public RuleCall getNotificationsNotificationParserRuleCall_12_2_0() { return cNotificationsNotificationParserRuleCall_12_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12_3() { return cRightCurlyBracketKeyword_12_3; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}
	public class LieuElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.evms.Evms.Lieu");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLieuKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cNomKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNomAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNomSTRINGTerminalRuleCall_4_0 = (RuleCall)cNomAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAdresseKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cAdresseAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cAdresseSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cAdresseAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCapaciteKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cCapaciteAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cCapaciteINTTerminalRuleCall_6_1_0 = (RuleCall)cCapaciteAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//// ====================== Lieu ======================
		//Lieu:
		//    'lieu' name=ID '{'
		//        'nom' nom=STRING
		//        ('adresse' adresse=STRING)?
		//        ('capacite' capacite=INT)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'lieu' name=ID '{'
		//    'nom' nom=STRING
		//    ('adresse' adresse=STRING)?
		//    ('capacite' capacite=INT)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'lieu'
		public Keyword getLieuKeyword_0() { return cLieuKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'nom'
		public Keyword getNomKeyword_3() { return cNomKeyword_3; }
		
		//nom=STRING
		public Assignment getNomAssignment_4() { return cNomAssignment_4; }
		
		//STRING
		public RuleCall getNomSTRINGTerminalRuleCall_4_0() { return cNomSTRINGTerminalRuleCall_4_0; }
		
		//('adresse' adresse=STRING)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'adresse'
		public Keyword getAdresseKeyword_5_0() { return cAdresseKeyword_5_0; }
		
		//adresse=STRING
		public Assignment getAdresseAssignment_5_1() { return cAdresseAssignment_5_1; }
		
		//STRING
		public RuleCall getAdresseSTRINGTerminalRuleCall_5_1_0() { return cAdresseSTRINGTerminalRuleCall_5_1_0; }
		
		//('capacite' capacite=INT)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'capacite'
		public Keyword getCapaciteKeyword_6_0() { return cCapaciteKeyword_6_0; }
		
		//capacite=INT
		public Assignment getCapaciteAssignment_6_1() { return cCapaciteAssignment_6_1; }
		
		//INT
		public RuleCall getCapaciteINTTerminalRuleCall_6_1_0() { return cCapaciteINTTerminalRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class UtilisateurElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.evms.Evms.Utilisateur");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUtilisateurKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cNomKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNomAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNomSTRINGTerminalRuleCall_4_0 = (RuleCall)cNomAssignment_4.eContents().get(0);
		private final Keyword cEmailKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cEmailAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cEmailSTRINGTerminalRuleCall_6_0 = (RuleCall)cEmailAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cRoleKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cRoleAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final Alternatives cRoleAlternatives_7_1_0 = (Alternatives)cRoleAssignment_7_1.eContents().get(0);
		private final Keyword cRoleOrganisateurKeyword_7_1_0_0 = (Keyword)cRoleAlternatives_7_1_0.eContents().get(0);
		private final Keyword cRoleParticipantKeyword_7_1_0_1 = (Keyword)cRoleAlternatives_7_1_0.eContents().get(1);
		private final Keyword cRoleAdminKeyword_7_1_0_2 = (Keyword)cRoleAlternatives_7_1_0.eContents().get(2);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cMotDePasseKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cMotDePasseAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cMotDePasseSTRINGTerminalRuleCall_8_1_0 = (RuleCall)cMotDePasseAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//// ====================== Utilisateur ======================
		//Utilisateur:
		//    'utilisateur' name=ID '{'
		//        'nom' nom=STRING
		//        'email' email=STRING
		//        ('role' role=('organisateur'|'participant'|'admin'))?
		//        ('motDePasse' motDePasse=STRING)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'utilisateur' name=ID '{'
		//    'nom' nom=STRING
		//    'email' email=STRING
		//    ('role' role=('organisateur'|'participant'|'admin'))?
		//    ('motDePasse' motDePasse=STRING)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'utilisateur'
		public Keyword getUtilisateurKeyword_0() { return cUtilisateurKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'nom'
		public Keyword getNomKeyword_3() { return cNomKeyword_3; }
		
		//nom=STRING
		public Assignment getNomAssignment_4() { return cNomAssignment_4; }
		
		//STRING
		public RuleCall getNomSTRINGTerminalRuleCall_4_0() { return cNomSTRINGTerminalRuleCall_4_0; }
		
		//'email'
		public Keyword getEmailKeyword_5() { return cEmailKeyword_5; }
		
		//email=STRING
		public Assignment getEmailAssignment_6() { return cEmailAssignment_6; }
		
		//STRING
		public RuleCall getEmailSTRINGTerminalRuleCall_6_0() { return cEmailSTRINGTerminalRuleCall_6_0; }
		
		//('role' role=('organisateur'|'participant'|'admin'))?
		public Group getGroup_7() { return cGroup_7; }
		
		//'role'
		public Keyword getRoleKeyword_7_0() { return cRoleKeyword_7_0; }
		
		//role=('organisateur'|'participant'|'admin')
		public Assignment getRoleAssignment_7_1() { return cRoleAssignment_7_1; }
		
		//('organisateur'|'participant'|'admin')
		public Alternatives getRoleAlternatives_7_1_0() { return cRoleAlternatives_7_1_0; }
		
		//'organisateur'
		public Keyword getRoleOrganisateurKeyword_7_1_0_0() { return cRoleOrganisateurKeyword_7_1_0_0; }
		
		//'participant'
		public Keyword getRoleParticipantKeyword_7_1_0_1() { return cRoleParticipantKeyword_7_1_0_1; }
		
		//'admin'
		public Keyword getRoleAdminKeyword_7_1_0_2() { return cRoleAdminKeyword_7_1_0_2; }
		
		//('motDePasse' motDePasse=STRING)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'motDePasse'
		public Keyword getMotDePasseKeyword_8_0() { return cMotDePasseKeyword_8_0; }
		
		//motDePasse=STRING
		public Assignment getMotDePasseAssignment_8_1() { return cMotDePasseAssignment_8_1; }
		
		//STRING
		public RuleCall getMotDePasseSTRINGTerminalRuleCall_8_1_0() { return cMotDePasseSTRINGTerminalRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class InscriptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.evms.Evms.Inscription");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInscriptionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cUtilisateurKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cUtilisateurAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cUtilisateurUtilisateurCrossReference_3_0 = (CrossReference)cUtilisateurAssignment_3.eContents().get(0);
		private final RuleCall cUtilisateurUtilisateurIDTerminalRuleCall_3_0_1 = (RuleCall)cUtilisateurUtilisateurCrossReference_3_0.eContents().get(1);
		private final Keyword cEvenementKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cEvenementAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cEvenementEvenementCrossReference_5_0 = (CrossReference)cEvenementAssignment_5.eContents().get(0);
		private final RuleCall cEvenementEvenementIDTerminalRuleCall_5_0_1 = (RuleCall)cEvenementEvenementCrossReference_5_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//// ====================== Inscription ======================
		//Inscription:
		//    'inscription' '{'
		//        'utilisateur' utilisateur=[Utilisateur]
		//        'evenement' evenement=[Evenement]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'inscription' '{'
		//    'utilisateur' utilisateur=[Utilisateur]
		//    'evenement' evenement=[Evenement]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'inscription'
		public Keyword getInscriptionKeyword_0() { return cInscriptionKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'utilisateur'
		public Keyword getUtilisateurKeyword_2() { return cUtilisateurKeyword_2; }
		
		//utilisateur=[Utilisateur]
		public Assignment getUtilisateurAssignment_3() { return cUtilisateurAssignment_3; }
		
		//[Utilisateur]
		public CrossReference getUtilisateurUtilisateurCrossReference_3_0() { return cUtilisateurUtilisateurCrossReference_3_0; }
		
		//ID
		public RuleCall getUtilisateurUtilisateurIDTerminalRuleCall_3_0_1() { return cUtilisateurUtilisateurIDTerminalRuleCall_3_0_1; }
		
		//'evenement'
		public Keyword getEvenementKeyword_4() { return cEvenementKeyword_4; }
		
		//evenement=[Evenement]
		public Assignment getEvenementAssignment_5() { return cEvenementAssignment_5; }
		
		//[Evenement]
		public CrossReference getEvenementEvenementCrossReference_5_0() { return cEvenementEvenementCrossReference_5_0; }
		
		//ID
		public RuleCall getEvenementEvenementIDTerminalRuleCall_5_0_1() { return cEvenementEvenementIDTerminalRuleCall_5_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class NotificationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.evms.Evms.Notification");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNotificationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cMessageKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cMessageAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMessageSTRINGTerminalRuleCall_3_0 = (RuleCall)cMessageAssignment_3.eContents().get(0);
		private final Keyword cDestinataireKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cDestinataireAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cDestinataireUtilisateurCrossReference_5_0 = (CrossReference)cDestinataireAssignment_5.eContents().get(0);
		private final RuleCall cDestinataireUtilisateurIDTerminalRuleCall_5_0_1 = (RuleCall)cDestinataireUtilisateurCrossReference_5_0.eContents().get(1);
		private final Keyword cEvenementKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cEvenementAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cEvenementEvenementCrossReference_7_0 = (CrossReference)cEvenementAssignment_7.eContents().get(0);
		private final RuleCall cEvenementEvenementIDTerminalRuleCall_7_0_1 = (RuleCall)cEvenementEvenementCrossReference_7_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//// ====================== Notification ======================
		//Notification:
		//    'notification' '{'
		//        'message' message=STRING
		//        'destinataire' destinataire=[Utilisateur]
		//        'evenement' evenement=[Evenement]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'notification' '{'
		//    'message' message=STRING
		//    'destinataire' destinataire=[Utilisateur]
		//    'evenement' evenement=[Evenement]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'notification'
		public Keyword getNotificationKeyword_0() { return cNotificationKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'message'
		public Keyword getMessageKeyword_2() { return cMessageKeyword_2; }
		
		//message=STRING
		public Assignment getMessageAssignment_3() { return cMessageAssignment_3; }
		
		//STRING
		public RuleCall getMessageSTRINGTerminalRuleCall_3_0() { return cMessageSTRINGTerminalRuleCall_3_0; }
		
		//'destinataire'
		public Keyword getDestinataireKeyword_4() { return cDestinataireKeyword_4; }
		
		//destinataire=[Utilisateur]
		public Assignment getDestinataireAssignment_5() { return cDestinataireAssignment_5; }
		
		//[Utilisateur]
		public CrossReference getDestinataireUtilisateurCrossReference_5_0() { return cDestinataireUtilisateurCrossReference_5_0; }
		
		//ID
		public RuleCall getDestinataireUtilisateurIDTerminalRuleCall_5_0_1() { return cDestinataireUtilisateurIDTerminalRuleCall_5_0_1; }
		
		//'evenement'
		public Keyword getEvenementKeyword_6() { return cEvenementKeyword_6; }
		
		//evenement=[Evenement]
		public Assignment getEvenementAssignment_7() { return cEvenementAssignment_7; }
		
		//[Evenement]
		public CrossReference getEvenementEvenementCrossReference_7_0() { return cEvenementEvenementCrossReference_7_0; }
		
		//ID
		public RuleCall getEvenementEvenementIDTerminalRuleCall_7_0_1() { return cEvenementEvenementIDTerminalRuleCall_7_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	
	
	private final ModelElements pModel;
	private final RootElementElements pRootElement;
	private final TerminalRule tDATE;
	private final EvenementElements pEvenement;
	private final LieuElements pLieu;
	private final UtilisateurElements pUtilisateur;
	private final InscriptionElements pInscription;
	private final NotificationElements pNotification;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public EvmsGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pRootElement = new RootElementElements();
		this.tDATE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.evms.Evms.DATE");
		this.pEvenement = new EvenementElements();
		this.pLieu = new LieuElements();
		this.pUtilisateur = new UtilisateurElements();
		this.pInscription = new InscriptionElements();
		this.pNotification = new NotificationElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.example.evms.Evms".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    (elements+=RootElement)*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//RootElement:
	//      Evenement
	//    | Lieu
	//    | Utilisateur
	//    | Inscription
	//    | Notification;
	public RootElementElements getRootElementAccess() {
		return pRootElement;
	}
	
	public ParserRule getRootElementRule() {
		return getRootElementAccess().getRule();
	}
	
	//terminal DATE : '\'' INT '-' INT '-' INT ('T' INT ':' INT (':' INT)?)? '\'';
	public TerminalRule getDATERule() {
		return tDATE;
	}
	
	//// ====================== Evenement ======================
	//Evenement:
	//    'evenement' name=ID '{'
	//        ('titre' titre=STRING)?
	//        ('description' description=STRING)?
	//        ('debut' dateDebut=DATE)?
	//        ('fin' dateFin=DATE)?
	//        'lieu' lieu=[Lieu]
	//        'organisateur' createur=[Utilisateur]
	//        ('inscriptions' '{' inscriptions+=Inscription* '}')?
	//        ('notifications' '{' notifications+=Notification* '}')?
	//    '}';
	public EvenementElements getEvenementAccess() {
		return pEvenement;
	}
	
	public ParserRule getEvenementRule() {
		return getEvenementAccess().getRule();
	}
	
	//// ====================== Lieu ======================
	//Lieu:
	//    'lieu' name=ID '{'
	//        'nom' nom=STRING
	//        ('adresse' adresse=STRING)?
	//        ('capacite' capacite=INT)?
	//    '}';
	public LieuElements getLieuAccess() {
		return pLieu;
	}
	
	public ParserRule getLieuRule() {
		return getLieuAccess().getRule();
	}
	
	//// ====================== Utilisateur ======================
	//Utilisateur:
	//    'utilisateur' name=ID '{'
	//        'nom' nom=STRING
	//        'email' email=STRING
	//        ('role' role=('organisateur'|'participant'|'admin'))?
	//        ('motDePasse' motDePasse=STRING)?
	//    '}';
	public UtilisateurElements getUtilisateurAccess() {
		return pUtilisateur;
	}
	
	public ParserRule getUtilisateurRule() {
		return getUtilisateurAccess().getRule();
	}
	
	//// ====================== Inscription ======================
	//Inscription:
	//    'inscription' '{'
	//        'utilisateur' utilisateur=[Utilisateur]
	//        'evenement' evenement=[Evenement]
	//    '}';
	public InscriptionElements getInscriptionAccess() {
		return pInscription;
	}
	
	public ParserRule getInscriptionRule() {
		return getInscriptionAccess().getRule();
	}
	
	//// ====================== Notification ======================
	//Notification:
	//    'notification' '{'
	//        'message' message=STRING
	//        'destinataire' destinataire=[Utilisateur]
	//        'evenement' evenement=[Evenement]
	//    '}';
	public NotificationElements getNotificationAccess() {
		return pNotification;
	}
	
	public ParserRule getNotificationRule() {
		return getNotificationAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
