/*
 * generated by Xtext 2.36.0
 */
package org.example.evms.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.example.evms.EvmsRuntimeModule;
import org.example.evms.EvmsStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EvmsIdeSetup extends EvmsStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EvmsRuntimeModule(), new EvmsIdeModule()));
	}
	
}
