/*
 * generated by Xtext 2.36.0
 */
package org.example.evms.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.example.evms.ide.contentassist.antlr.internal.InternalEvmsParser;
import org.example.evms.services.EvmsGrammarAccess;

public class EvmsParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(EvmsGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, EvmsGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getRootElementAccess().getAlternatives(), "rule__RootElement__Alternatives");
			builder.put(grammarAccess.getUtilisateurAccess().getRoleAlternatives_7_1_0(), "rule__Utilisateur__RoleAlternatives_7_1_0");
			builder.put(grammarAccess.getEvenementAccess().getGroup(), "rule__Evenement__Group__0");
			builder.put(grammarAccess.getEvenementAccess().getGroup_3(), "rule__Evenement__Group_3__0");
			builder.put(grammarAccess.getEvenementAccess().getGroup_4(), "rule__Evenement__Group_4__0");
			builder.put(grammarAccess.getEvenementAccess().getGroup_5(), "rule__Evenement__Group_5__0");
			builder.put(grammarAccess.getEvenementAccess().getGroup_6(), "rule__Evenement__Group_6__0");
			builder.put(grammarAccess.getEvenementAccess().getGroup_11(), "rule__Evenement__Group_11__0");
			builder.put(grammarAccess.getEvenementAccess().getGroup_12(), "rule__Evenement__Group_12__0");
			builder.put(grammarAccess.getLieuAccess().getGroup(), "rule__Lieu__Group__0");
			builder.put(grammarAccess.getLieuAccess().getGroup_5(), "rule__Lieu__Group_5__0");
			builder.put(grammarAccess.getLieuAccess().getGroup_6(), "rule__Lieu__Group_6__0");
			builder.put(grammarAccess.getUtilisateurAccess().getGroup(), "rule__Utilisateur__Group__0");
			builder.put(grammarAccess.getUtilisateurAccess().getGroup_7(), "rule__Utilisateur__Group_7__0");
			builder.put(grammarAccess.getUtilisateurAccess().getGroup_8(), "rule__Utilisateur__Group_8__0");
			builder.put(grammarAccess.getInscriptionAccess().getGroup(), "rule__Inscription__Group__0");
			builder.put(grammarAccess.getNotificationAccess().getGroup(), "rule__Notification__Group__0");
			builder.put(grammarAccess.getModelAccess().getElementsAssignment(), "rule__Model__ElementsAssignment");
			builder.put(grammarAccess.getEvenementAccess().getNameAssignment_1(), "rule__Evenement__NameAssignment_1");
			builder.put(grammarAccess.getEvenementAccess().getTitreAssignment_3_1(), "rule__Evenement__TitreAssignment_3_1");
			builder.put(grammarAccess.getEvenementAccess().getDescriptionAssignment_4_1(), "rule__Evenement__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getEvenementAccess().getDateDebutAssignment_5_1(), "rule__Evenement__DateDebutAssignment_5_1");
			builder.put(grammarAccess.getEvenementAccess().getDateFinAssignment_6_1(), "rule__Evenement__DateFinAssignment_6_1");
			builder.put(grammarAccess.getEvenementAccess().getLieuAssignment_8(), "rule__Evenement__LieuAssignment_8");
			builder.put(grammarAccess.getEvenementAccess().getCreateurAssignment_10(), "rule__Evenement__CreateurAssignment_10");
			builder.put(grammarAccess.getEvenementAccess().getInscriptionsAssignment_11_2(), "rule__Evenement__InscriptionsAssignment_11_2");
			builder.put(grammarAccess.getEvenementAccess().getNotificationsAssignment_12_2(), "rule__Evenement__NotificationsAssignment_12_2");
			builder.put(grammarAccess.getLieuAccess().getNameAssignment_1(), "rule__Lieu__NameAssignment_1");
			builder.put(grammarAccess.getLieuAccess().getNomAssignment_4(), "rule__Lieu__NomAssignment_4");
			builder.put(grammarAccess.getLieuAccess().getAdresseAssignment_5_1(), "rule__Lieu__AdresseAssignment_5_1");
			builder.put(grammarAccess.getLieuAccess().getCapaciteAssignment_6_1(), "rule__Lieu__CapaciteAssignment_6_1");
			builder.put(grammarAccess.getUtilisateurAccess().getNameAssignment_1(), "rule__Utilisateur__NameAssignment_1");
			builder.put(grammarAccess.getUtilisateurAccess().getNomAssignment_4(), "rule__Utilisateur__NomAssignment_4");
			builder.put(grammarAccess.getUtilisateurAccess().getEmailAssignment_6(), "rule__Utilisateur__EmailAssignment_6");
			builder.put(grammarAccess.getUtilisateurAccess().getRoleAssignment_7_1(), "rule__Utilisateur__RoleAssignment_7_1");
			builder.put(grammarAccess.getUtilisateurAccess().getMotDePasseAssignment_8_1(), "rule__Utilisateur__MotDePasseAssignment_8_1");
			builder.put(grammarAccess.getInscriptionAccess().getUtilisateurAssignment_3(), "rule__Inscription__UtilisateurAssignment_3");
			builder.put(grammarAccess.getInscriptionAccess().getEvenementAssignment_5(), "rule__Inscription__EvenementAssignment_5");
			builder.put(grammarAccess.getNotificationAccess().getMessageAssignment_3(), "rule__Notification__MessageAssignment_3");
			builder.put(grammarAccess.getNotificationAccess().getDestinataireAssignment_5(), "rule__Notification__DestinataireAssignment_5");
			builder.put(grammarAccess.getNotificationAccess().getEvenementAssignment_7(), "rule__Notification__EvenementAssignment_7");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private EvmsGrammarAccess grammarAccess;

	@Override
	protected InternalEvmsParser createParser() {
		InternalEvmsParser result = new InternalEvmsParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public EvmsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EvmsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
