/*
 * generated by Xtext 2.36.0
 */
package org.example.evms.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class EvmsUiModule extends AbstractEvmsUiModule {

	public EvmsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
