/**
 * generated by Xtext 2.36.0
 */
package org.example.evms.evms.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.example.evms.evms.Evenement;
import org.example.evms.evms.EvmsPackage;
import org.example.evms.evms.Inscription;
import org.example.evms.evms.Lieu;
import org.example.evms.evms.Notification;
import org.example.evms.evms.Utilisateur;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Evenement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.evms.evms.impl.EvenementImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.example.evms.evms.impl.EvenementImpl#getTitre <em>Titre</em>}</li>
 *   <li>{@link org.example.evms.evms.impl.EvenementImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link org.example.evms.evms.impl.EvenementImpl#getDateDebut <em>Date Debut</em>}</li>
 *   <li>{@link org.example.evms.evms.impl.EvenementImpl#getDateFin <em>Date Fin</em>}</li>
 *   <li>{@link org.example.evms.evms.impl.EvenementImpl#getLieu <em>Lieu</em>}</li>
 *   <li>{@link org.example.evms.evms.impl.EvenementImpl#getCreateur <em>Createur</em>}</li>
 *   <li>{@link org.example.evms.evms.impl.EvenementImpl#getInscriptions <em>Inscriptions</em>}</li>
 *   <li>{@link org.example.evms.evms.impl.EvenementImpl#getNotifications <em>Notifications</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EvenementImpl extends RootElementImpl implements Evenement
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getTitre() <em>Titre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitre()
   * @generated
   * @ordered
   */
  protected static final String TITRE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTitre() <em>Titre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitre()
   * @generated
   * @ordered
   */
  protected String titre = TITRE_EDEFAULT;

  /**
   * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected String description = DESCRIPTION_EDEFAULT;

  /**
   * The default value of the '{@link #getDateDebut() <em>Date Debut</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDateDebut()
   * @generated
   * @ordered
   */
  protected static final String DATE_DEBUT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDateDebut() <em>Date Debut</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDateDebut()
   * @generated
   * @ordered
   */
  protected String dateDebut = DATE_DEBUT_EDEFAULT;

  /**
   * The default value of the '{@link #getDateFin() <em>Date Fin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDateFin()
   * @generated
   * @ordered
   */
  protected static final String DATE_FIN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDateFin() <em>Date Fin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDateFin()
   * @generated
   * @ordered
   */
  protected String dateFin = DATE_FIN_EDEFAULT;

  /**
   * The cached value of the '{@link #getLieu() <em>Lieu</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLieu()
   * @generated
   * @ordered
   */
  protected Lieu lieu;

  /**
   * The cached value of the '{@link #getCreateur() <em>Createur</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCreateur()
   * @generated
   * @ordered
   */
  protected Utilisateur createur;

  /**
   * The cached value of the '{@link #getInscriptions() <em>Inscriptions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInscriptions()
   * @generated
   * @ordered
   */
  protected EList<Inscription> inscriptions;

  /**
   * The cached value of the '{@link #getNotifications() <em>Notifications</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNotifications()
   * @generated
   * @ordered
   */
  protected EList<Notification> notifications;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EvenementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EvmsPackage.Literals.EVENEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, org.eclipse.emf.common.notify.Notification.SET, EvmsPackage.EVENEMENT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTitre()
  {
    return titre;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTitre(String newTitre)
  {
    String oldTitre = titre;
    titre = newTitre;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, org.eclipse.emf.common.notify.Notification.SET, EvmsPackage.EVENEMENT__TITRE, oldTitre, titre));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescription(String newDescription)
  {
    String oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, org.eclipse.emf.common.notify.Notification.SET, EvmsPackage.EVENEMENT__DESCRIPTION, oldDescription, description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDateDebut()
  {
    return dateDebut;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDateDebut(String newDateDebut)
  {
    String oldDateDebut = dateDebut;
    dateDebut = newDateDebut;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, org.eclipse.emf.common.notify.Notification.SET, EvmsPackage.EVENEMENT__DATE_DEBUT, oldDateDebut, dateDebut));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDateFin()
  {
    return dateFin;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDateFin(String newDateFin)
  {
    String oldDateFin = dateFin;
    dateFin = newDateFin;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, org.eclipse.emf.common.notify.Notification.SET, EvmsPackage.EVENEMENT__DATE_FIN, oldDateFin, dateFin));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Lieu getLieu()
  {
    if (lieu != null && lieu.eIsProxy())
    {
      InternalEObject oldLieu = (InternalEObject)lieu;
      lieu = (Lieu)eResolveProxy(oldLieu);
      if (lieu != oldLieu)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, org.eclipse.emf.common.notify.Notification.RESOLVE, EvmsPackage.EVENEMENT__LIEU, oldLieu, lieu));
      }
    }
    return lieu;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Lieu basicGetLieu()
  {
    return lieu;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLieu(Lieu newLieu)
  {
    Lieu oldLieu = lieu;
    lieu = newLieu;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, org.eclipse.emf.common.notify.Notification.SET, EvmsPackage.EVENEMENT__LIEU, oldLieu, lieu));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Utilisateur getCreateur()
  {
    if (createur != null && createur.eIsProxy())
    {
      InternalEObject oldCreateur = (InternalEObject)createur;
      createur = (Utilisateur)eResolveProxy(oldCreateur);
      if (createur != oldCreateur)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, org.eclipse.emf.common.notify.Notification.RESOLVE, EvmsPackage.EVENEMENT__CREATEUR, oldCreateur, createur));
      }
    }
    return createur;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Utilisateur basicGetCreateur()
  {
    return createur;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCreateur(Utilisateur newCreateur)
  {
    Utilisateur oldCreateur = createur;
    createur = newCreateur;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, org.eclipse.emf.common.notify.Notification.SET, EvmsPackage.EVENEMENT__CREATEUR, oldCreateur, createur));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Inscription> getInscriptions()
  {
    if (inscriptions == null)
    {
      inscriptions = new EObjectContainmentEList<Inscription>(Inscription.class, this, EvmsPackage.EVENEMENT__INSCRIPTIONS);
    }
    return inscriptions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Notification> getNotifications()
  {
    if (notifications == null)
    {
      notifications = new EObjectContainmentEList<Notification>(Notification.class, this, EvmsPackage.EVENEMENT__NOTIFICATIONS);
    }
    return notifications;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EvmsPackage.EVENEMENT__INSCRIPTIONS:
        return ((InternalEList<?>)getInscriptions()).basicRemove(otherEnd, msgs);
      case EvmsPackage.EVENEMENT__NOTIFICATIONS:
        return ((InternalEList<?>)getNotifications()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EvmsPackage.EVENEMENT__NAME:
        return getName();
      case EvmsPackage.EVENEMENT__TITRE:
        return getTitre();
      case EvmsPackage.EVENEMENT__DESCRIPTION:
        return getDescription();
      case EvmsPackage.EVENEMENT__DATE_DEBUT:
        return getDateDebut();
      case EvmsPackage.EVENEMENT__DATE_FIN:
        return getDateFin();
      case EvmsPackage.EVENEMENT__LIEU:
        if (resolve) return getLieu();
        return basicGetLieu();
      case EvmsPackage.EVENEMENT__CREATEUR:
        if (resolve) return getCreateur();
        return basicGetCreateur();
      case EvmsPackage.EVENEMENT__INSCRIPTIONS:
        return getInscriptions();
      case EvmsPackage.EVENEMENT__NOTIFICATIONS:
        return getNotifications();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EvmsPackage.EVENEMENT__NAME:
        setName((String)newValue);
        return;
      case EvmsPackage.EVENEMENT__TITRE:
        setTitre((String)newValue);
        return;
      case EvmsPackage.EVENEMENT__DESCRIPTION:
        setDescription((String)newValue);
        return;
      case EvmsPackage.EVENEMENT__DATE_DEBUT:
        setDateDebut((String)newValue);
        return;
      case EvmsPackage.EVENEMENT__DATE_FIN:
        setDateFin((String)newValue);
        return;
      case EvmsPackage.EVENEMENT__LIEU:
        setLieu((Lieu)newValue);
        return;
      case EvmsPackage.EVENEMENT__CREATEUR:
        setCreateur((Utilisateur)newValue);
        return;
      case EvmsPackage.EVENEMENT__INSCRIPTIONS:
        getInscriptions().clear();
        getInscriptions().addAll((Collection<? extends Inscription>)newValue);
        return;
      case EvmsPackage.EVENEMENT__NOTIFICATIONS:
        getNotifications().clear();
        getNotifications().addAll((Collection<? extends Notification>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EvmsPackage.EVENEMENT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case EvmsPackage.EVENEMENT__TITRE:
        setTitre(TITRE_EDEFAULT);
        return;
      case EvmsPackage.EVENEMENT__DESCRIPTION:
        setDescription(DESCRIPTION_EDEFAULT);
        return;
      case EvmsPackage.EVENEMENT__DATE_DEBUT:
        setDateDebut(DATE_DEBUT_EDEFAULT);
        return;
      case EvmsPackage.EVENEMENT__DATE_FIN:
        setDateFin(DATE_FIN_EDEFAULT);
        return;
      case EvmsPackage.EVENEMENT__LIEU:
        setLieu((Lieu)null);
        return;
      case EvmsPackage.EVENEMENT__CREATEUR:
        setCreateur((Utilisateur)null);
        return;
      case EvmsPackage.EVENEMENT__INSCRIPTIONS:
        getInscriptions().clear();
        return;
      case EvmsPackage.EVENEMENT__NOTIFICATIONS:
        getNotifications().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EvmsPackage.EVENEMENT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case EvmsPackage.EVENEMENT__TITRE:
        return TITRE_EDEFAULT == null ? titre != null : !TITRE_EDEFAULT.equals(titre);
      case EvmsPackage.EVENEMENT__DESCRIPTION:
        return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
      case EvmsPackage.EVENEMENT__DATE_DEBUT:
        return DATE_DEBUT_EDEFAULT == null ? dateDebut != null : !DATE_DEBUT_EDEFAULT.equals(dateDebut);
      case EvmsPackage.EVENEMENT__DATE_FIN:
        return DATE_FIN_EDEFAULT == null ? dateFin != null : !DATE_FIN_EDEFAULT.equals(dateFin);
      case EvmsPackage.EVENEMENT__LIEU:
        return lieu != null;
      case EvmsPackage.EVENEMENT__CREATEUR:
        return createur != null;
      case EvmsPackage.EVENEMENT__INSCRIPTIONS:
        return inscriptions != null && !inscriptions.isEmpty();
      case EvmsPackage.EVENEMENT__NOTIFICATIONS:
        return notifications != null && !notifications.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", titre: ");
    result.append(titre);
    result.append(", description: ");
    result.append(description);
    result.append(", dateDebut: ");
    result.append(dateDebut);
    result.append(", dateFin: ");
    result.append(dateFin);
    result.append(')');
    return result.toString();
  }

} //EvenementImpl
