/**
 * generated by Xtext 2.36.0
 */
package org.example.evms.evms.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.example.evms.evms.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class EvmsFactoryImpl extends EFactoryImpl implements EvmsFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static EvmsFactory init()
  {
    try
    {
      EvmsFactory theEvmsFactory = (EvmsFactory)EPackage.Registry.INSTANCE.getEFactory(EvmsPackage.eNS_URI);
      if (theEvmsFactory != null)
      {
        return theEvmsFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new EvmsFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EvmsFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case EvmsPackage.MODEL: return createModel();
      case EvmsPackage.ROOT_ELEMENT: return createRootElement();
      case EvmsPackage.EVENEMENT: return createEvenement();
      case EvmsPackage.LIEU: return createLieu();
      case EvmsPackage.UTILISATEUR: return createUtilisateur();
      case EvmsPackage.INSCRIPTION: return createInscription();
      case EvmsPackage.NOTIFICATION: return createNotification();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RootElement createRootElement()
  {
    RootElementImpl rootElement = new RootElementImpl();
    return rootElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Evenement createEvenement()
  {
    EvenementImpl evenement = new EvenementImpl();
    return evenement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Lieu createLieu()
  {
    LieuImpl lieu = new LieuImpl();
    return lieu;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Utilisateur createUtilisateur()
  {
    UtilisateurImpl utilisateur = new UtilisateurImpl();
    return utilisateur;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Inscription createInscription()
  {
    InscriptionImpl inscription = new InscriptionImpl();
    return inscription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Notification createNotification()
  {
    NotificationImpl notification = new NotificationImpl();
    return notification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EvmsPackage getEvmsPackage()
  {
    return (EvmsPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static EvmsPackage getPackage()
  {
    return EvmsPackage.eINSTANCE;
  }

} //EvmsFactoryImpl
