/**
 * generated by Xtext 2.36.0
 */
package org.example.evms.evms.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.example.evms.evms.Evenement;
import org.example.evms.evms.EvmsPackage;
import org.example.evms.evms.Inscription;
import org.example.evms.evms.Utilisateur;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Inscription</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.evms.evms.impl.InscriptionImpl#getUtilisateur <em>Utilisateur</em>}</li>
 *   <li>{@link org.example.evms.evms.impl.InscriptionImpl#getEvenement <em>Evenement</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InscriptionImpl extends RootElementImpl implements Inscription
{
  /**
   * The cached value of the '{@link #getUtilisateur() <em>Utilisateur</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUtilisateur()
   * @generated
   * @ordered
   */
  protected Utilisateur utilisateur;

  /**
   * The cached value of the '{@link #getEvenement() <em>Evenement</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEvenement()
   * @generated
   * @ordered
   */
  protected Evenement evenement;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InscriptionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EvmsPackage.Literals.INSCRIPTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Utilisateur getUtilisateur()
  {
    if (utilisateur != null && utilisateur.eIsProxy())
    {
      InternalEObject oldUtilisateur = (InternalEObject)utilisateur;
      utilisateur = (Utilisateur)eResolveProxy(oldUtilisateur);
      if (utilisateur != oldUtilisateur)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, EvmsPackage.INSCRIPTION__UTILISATEUR, oldUtilisateur, utilisateur));
      }
    }
    return utilisateur;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Utilisateur basicGetUtilisateur()
  {
    return utilisateur;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUtilisateur(Utilisateur newUtilisateur)
  {
    Utilisateur oldUtilisateur = utilisateur;
    utilisateur = newUtilisateur;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EvmsPackage.INSCRIPTION__UTILISATEUR, oldUtilisateur, utilisateur));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Evenement getEvenement()
  {
    if (evenement != null && evenement.eIsProxy())
    {
      InternalEObject oldEvenement = (InternalEObject)evenement;
      evenement = (Evenement)eResolveProxy(oldEvenement);
      if (evenement != oldEvenement)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, EvmsPackage.INSCRIPTION__EVENEMENT, oldEvenement, evenement));
      }
    }
    return evenement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Evenement basicGetEvenement()
  {
    return evenement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEvenement(Evenement newEvenement)
  {
    Evenement oldEvenement = evenement;
    evenement = newEvenement;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EvmsPackage.INSCRIPTION__EVENEMENT, oldEvenement, evenement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EvmsPackage.INSCRIPTION__UTILISATEUR:
        if (resolve) return getUtilisateur();
        return basicGetUtilisateur();
      case EvmsPackage.INSCRIPTION__EVENEMENT:
        if (resolve) return getEvenement();
        return basicGetEvenement();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EvmsPackage.INSCRIPTION__UTILISATEUR:
        setUtilisateur((Utilisateur)newValue);
        return;
      case EvmsPackage.INSCRIPTION__EVENEMENT:
        setEvenement((Evenement)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EvmsPackage.INSCRIPTION__UTILISATEUR:
        setUtilisateur((Utilisateur)null);
        return;
      case EvmsPackage.INSCRIPTION__EVENEMENT:
        setEvenement((Evenement)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EvmsPackage.INSCRIPTION__UTILISATEUR:
        return utilisateur != null;
      case EvmsPackage.INSCRIPTION__EVENEMENT:
        return evenement != null;
    }
    return super.eIsSet(featureID);
  }

} //InscriptionImpl
