/**
 * generated by Xtext 2.36.0
 */
package org.example.evms.evms.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.example.evms.evms.EvmsPackage;
import org.example.evms.evms.Lieu;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Lieu</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.evms.evms.impl.LieuImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.example.evms.evms.impl.LieuImpl#getNom <em>Nom</em>}</li>
 *   <li>{@link org.example.evms.evms.impl.LieuImpl#getAdresse <em>Adresse</em>}</li>
 *   <li>{@link org.example.evms.evms.impl.LieuImpl#getCapacite <em>Capacite</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LieuImpl extends RootElementImpl implements Lieu
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getNom() <em>Nom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNom()
   * @generated
   * @ordered
   */
  protected static final String NOM_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNom() <em>Nom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNom()
   * @generated
   * @ordered
   */
  protected String nom = NOM_EDEFAULT;

  /**
   * The default value of the '{@link #getAdresse() <em>Adresse</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAdresse()
   * @generated
   * @ordered
   */
  protected static final String ADRESSE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAdresse() <em>Adresse</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAdresse()
   * @generated
   * @ordered
   */
  protected String adresse = ADRESSE_EDEFAULT;

  /**
   * The default value of the '{@link #getCapacite() <em>Capacite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCapacite()
   * @generated
   * @ordered
   */
  protected static final int CAPACITE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getCapacite() <em>Capacite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCapacite()
   * @generated
   * @ordered
   */
  protected int capacite = CAPACITE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LieuImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EvmsPackage.Literals.LIEU;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EvmsPackage.LIEU__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNom()
  {
    return nom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNom(String newNom)
  {
    String oldNom = nom;
    nom = newNom;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EvmsPackage.LIEU__NOM, oldNom, nom));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAdresse()
  {
    return adresse;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAdresse(String newAdresse)
  {
    String oldAdresse = adresse;
    adresse = newAdresse;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EvmsPackage.LIEU__ADRESSE, oldAdresse, adresse));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getCapacite()
  {
    return capacite;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCapacite(int newCapacite)
  {
    int oldCapacite = capacite;
    capacite = newCapacite;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EvmsPackage.LIEU__CAPACITE, oldCapacite, capacite));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EvmsPackage.LIEU__NAME:
        return getName();
      case EvmsPackage.LIEU__NOM:
        return getNom();
      case EvmsPackage.LIEU__ADRESSE:
        return getAdresse();
      case EvmsPackage.LIEU__CAPACITE:
        return getCapacite();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EvmsPackage.LIEU__NAME:
        setName((String)newValue);
        return;
      case EvmsPackage.LIEU__NOM:
        setNom((String)newValue);
        return;
      case EvmsPackage.LIEU__ADRESSE:
        setAdresse((String)newValue);
        return;
      case EvmsPackage.LIEU__CAPACITE:
        setCapacite((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EvmsPackage.LIEU__NAME:
        setName(NAME_EDEFAULT);
        return;
      case EvmsPackage.LIEU__NOM:
        setNom(NOM_EDEFAULT);
        return;
      case EvmsPackage.LIEU__ADRESSE:
        setAdresse(ADRESSE_EDEFAULT);
        return;
      case EvmsPackage.LIEU__CAPACITE:
        setCapacite(CAPACITE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EvmsPackage.LIEU__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case EvmsPackage.LIEU__NOM:
        return NOM_EDEFAULT == null ? nom != null : !NOM_EDEFAULT.equals(nom);
      case EvmsPackage.LIEU__ADRESSE:
        return ADRESSE_EDEFAULT == null ? adresse != null : !ADRESSE_EDEFAULT.equals(adresse);
      case EvmsPackage.LIEU__CAPACITE:
        return capacite != CAPACITE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", nom: ");
    result.append(nom);
    result.append(", adresse: ");
    result.append(adresse);
    result.append(", capacite: ");
    result.append(capacite);
    result.append(')');
    return result.toString();
  }

} //LieuImpl
