/**
 * generated by Xtext 2.36.0
 */
package org.example.evms.evms.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.example.evms.evms.Evenement;
import org.example.evms.evms.EvmsPackage;
import org.example.evms.evms.Notification;
import org.example.evms.evms.Utilisateur;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Notification</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.evms.evms.impl.NotificationImpl#getMessage <em>Message</em>}</li>
 *   <li>{@link org.example.evms.evms.impl.NotificationImpl#getDestinataire <em>Destinataire</em>}</li>
 *   <li>{@link org.example.evms.evms.impl.NotificationImpl#getEvenement <em>Evenement</em>}</li>
 * </ul>
 *
 * @generated
 */
public class NotificationImpl extends RootElementImpl implements Notification
{
  /**
   * The default value of the '{@link #getMessage() <em>Message</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMessage()
   * @generated
   * @ordered
   */
  protected static final String MESSAGE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMessage() <em>Message</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMessage()
   * @generated
   * @ordered
   */
  protected String message = MESSAGE_EDEFAULT;

  /**
   * The cached value of the '{@link #getDestinataire() <em>Destinataire</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDestinataire()
   * @generated
   * @ordered
   */
  protected Utilisateur destinataire;

  /**
   * The cached value of the '{@link #getEvenement() <em>Evenement</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEvenement()
   * @generated
   * @ordered
   */
  protected Evenement evenement;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NotificationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EvmsPackage.Literals.NOTIFICATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMessage()
  {
    return message;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMessage(String newMessage)
  {
    String oldMessage = message;
    message = newMessage;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, org.eclipse.emf.common.notify.Notification.SET, EvmsPackage.NOTIFICATION__MESSAGE, oldMessage, message));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Utilisateur getDestinataire()
  {
    if (destinataire != null && destinataire.eIsProxy())
    {
      InternalEObject oldDestinataire = (InternalEObject)destinataire;
      destinataire = (Utilisateur)eResolveProxy(oldDestinataire);
      if (destinataire != oldDestinataire)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, org.eclipse.emf.common.notify.Notification.RESOLVE, EvmsPackage.NOTIFICATION__DESTINATAIRE, oldDestinataire, destinataire));
      }
    }
    return destinataire;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Utilisateur basicGetDestinataire()
  {
    return destinataire;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDestinataire(Utilisateur newDestinataire)
  {
    Utilisateur oldDestinataire = destinataire;
    destinataire = newDestinataire;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, org.eclipse.emf.common.notify.Notification.SET, EvmsPackage.NOTIFICATION__DESTINATAIRE, oldDestinataire, destinataire));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Evenement getEvenement()
  {
    if (evenement != null && evenement.eIsProxy())
    {
      InternalEObject oldEvenement = (InternalEObject)evenement;
      evenement = (Evenement)eResolveProxy(oldEvenement);
      if (evenement != oldEvenement)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, org.eclipse.emf.common.notify.Notification.RESOLVE, EvmsPackage.NOTIFICATION__EVENEMENT, oldEvenement, evenement));
      }
    }
    return evenement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Evenement basicGetEvenement()
  {
    return evenement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEvenement(Evenement newEvenement)
  {
    Evenement oldEvenement = evenement;
    evenement = newEvenement;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, org.eclipse.emf.common.notify.Notification.SET, EvmsPackage.NOTIFICATION__EVENEMENT, oldEvenement, evenement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EvmsPackage.NOTIFICATION__MESSAGE:
        return getMessage();
      case EvmsPackage.NOTIFICATION__DESTINATAIRE:
        if (resolve) return getDestinataire();
        return basicGetDestinataire();
      case EvmsPackage.NOTIFICATION__EVENEMENT:
        if (resolve) return getEvenement();
        return basicGetEvenement();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EvmsPackage.NOTIFICATION__MESSAGE:
        setMessage((String)newValue);
        return;
      case EvmsPackage.NOTIFICATION__DESTINATAIRE:
        setDestinataire((Utilisateur)newValue);
        return;
      case EvmsPackage.NOTIFICATION__EVENEMENT:
        setEvenement((Evenement)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EvmsPackage.NOTIFICATION__MESSAGE:
        setMessage(MESSAGE_EDEFAULT);
        return;
      case EvmsPackage.NOTIFICATION__DESTINATAIRE:
        setDestinataire((Utilisateur)null);
        return;
      case EvmsPackage.NOTIFICATION__EVENEMENT:
        setEvenement((Evenement)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EvmsPackage.NOTIFICATION__MESSAGE:
        return MESSAGE_EDEFAULT == null ? message != null : !MESSAGE_EDEFAULT.equals(message);
      case EvmsPackage.NOTIFICATION__DESTINATAIRE:
        return destinataire != null;
      case EvmsPackage.NOTIFICATION__EVENEMENT:
        return evenement != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (message: ");
    result.append(message);
    result.append(')');
    return result.toString();
  }

} //NotificationImpl
