/**
 * generated by Xtext 2.36.0
 */
package org.example.evms.evms.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.example.evms.evms.EvmsPackage;
import org.example.evms.evms.RootElement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Root Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RootElementImpl extends MinimalEObjectImpl.Container implements RootElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RootElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EvmsPackage.Literals.ROOT_ELEMENT;
  }

} //RootElementImpl
