/**
 * generated by Xtext 2.36.0
 */
package org.example.evms.evms.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.example.evms.evms.EvmsPackage;
import org.example.evms.evms.Utilisateur;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Utilisateur</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.evms.evms.impl.UtilisateurImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.example.evms.evms.impl.UtilisateurImpl#getNom <em>Nom</em>}</li>
 *   <li>{@link org.example.evms.evms.impl.UtilisateurImpl#getEmail <em>Email</em>}</li>
 *   <li>{@link org.example.evms.evms.impl.UtilisateurImpl#getRole <em>Role</em>}</li>
 *   <li>{@link org.example.evms.evms.impl.UtilisateurImpl#getMotDePasse <em>Mot De Passe</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UtilisateurImpl extends RootElementImpl implements Utilisateur
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getNom() <em>Nom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNom()
   * @generated
   * @ordered
   */
  protected static final String NOM_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNom() <em>Nom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNom()
   * @generated
   * @ordered
   */
  protected String nom = NOM_EDEFAULT;

  /**
   * The default value of the '{@link #getEmail() <em>Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEmail()
   * @generated
   * @ordered
   */
  protected static final String EMAIL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEmail() <em>Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEmail()
   * @generated
   * @ordered
   */
  protected String email = EMAIL_EDEFAULT;

  /**
   * The default value of the '{@link #getRole() <em>Role</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRole()
   * @generated
   * @ordered
   */
  protected static final String ROLE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRole() <em>Role</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRole()
   * @generated
   * @ordered
   */
  protected String role = ROLE_EDEFAULT;

  /**
   * The default value of the '{@link #getMotDePasse() <em>Mot De Passe</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMotDePasse()
   * @generated
   * @ordered
   */
  protected static final String MOT_DE_PASSE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMotDePasse() <em>Mot De Passe</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMotDePasse()
   * @generated
   * @ordered
   */
  protected String motDePasse = MOT_DE_PASSE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UtilisateurImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EvmsPackage.Literals.UTILISATEUR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EvmsPackage.UTILISATEUR__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNom()
  {
    return nom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNom(String newNom)
  {
    String oldNom = nom;
    nom = newNom;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EvmsPackage.UTILISATEUR__NOM, oldNom, nom));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEmail()
  {
    return email;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEmail(String newEmail)
  {
    String oldEmail = email;
    email = newEmail;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EvmsPackage.UTILISATEUR__EMAIL, oldEmail, email));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRole()
  {
    return role;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRole(String newRole)
  {
    String oldRole = role;
    role = newRole;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EvmsPackage.UTILISATEUR__ROLE, oldRole, role));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMotDePasse()
  {
    return motDePasse;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMotDePasse(String newMotDePasse)
  {
    String oldMotDePasse = motDePasse;
    motDePasse = newMotDePasse;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EvmsPackage.UTILISATEUR__MOT_DE_PASSE, oldMotDePasse, motDePasse));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EvmsPackage.UTILISATEUR__NAME:
        return getName();
      case EvmsPackage.UTILISATEUR__NOM:
        return getNom();
      case EvmsPackage.UTILISATEUR__EMAIL:
        return getEmail();
      case EvmsPackage.UTILISATEUR__ROLE:
        return getRole();
      case EvmsPackage.UTILISATEUR__MOT_DE_PASSE:
        return getMotDePasse();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EvmsPackage.UTILISATEUR__NAME:
        setName((String)newValue);
        return;
      case EvmsPackage.UTILISATEUR__NOM:
        setNom((String)newValue);
        return;
      case EvmsPackage.UTILISATEUR__EMAIL:
        setEmail((String)newValue);
        return;
      case EvmsPackage.UTILISATEUR__ROLE:
        setRole((String)newValue);
        return;
      case EvmsPackage.UTILISATEUR__MOT_DE_PASSE:
        setMotDePasse((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EvmsPackage.UTILISATEUR__NAME:
        setName(NAME_EDEFAULT);
        return;
      case EvmsPackage.UTILISATEUR__NOM:
        setNom(NOM_EDEFAULT);
        return;
      case EvmsPackage.UTILISATEUR__EMAIL:
        setEmail(EMAIL_EDEFAULT);
        return;
      case EvmsPackage.UTILISATEUR__ROLE:
        setRole(ROLE_EDEFAULT);
        return;
      case EvmsPackage.UTILISATEUR__MOT_DE_PASSE:
        setMotDePasse(MOT_DE_PASSE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EvmsPackage.UTILISATEUR__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case EvmsPackage.UTILISATEUR__NOM:
        return NOM_EDEFAULT == null ? nom != null : !NOM_EDEFAULT.equals(nom);
      case EvmsPackage.UTILISATEUR__EMAIL:
        return EMAIL_EDEFAULT == null ? email != null : !EMAIL_EDEFAULT.equals(email);
      case EvmsPackage.UTILISATEUR__ROLE:
        return ROLE_EDEFAULT == null ? role != null : !ROLE_EDEFAULT.equals(role);
      case EvmsPackage.UTILISATEUR__MOT_DE_PASSE:
        return MOT_DE_PASSE_EDEFAULT == null ? motDePasse != null : !MOT_DE_PASSE_EDEFAULT.equals(motDePasse);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", nom: ");
    result.append(nom);
    result.append(", email: ");
    result.append(email);
    result.append(", role: ");
    result.append(role);
    result.append(", motDePasse: ");
    result.append(motDePasse);
    result.append(')');
    return result.toString();
  }

} //UtilisateurImpl
