/*
 * generated by Xtext 2.36.0
 */
package org.example.evms.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.example.evms.parser.antlr.internal.InternalEvmsParser;
import org.example.evms.services.EvmsGrammarAccess;

public class EvmsParser extends AbstractAntlrParser {

	@Inject
	private EvmsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEvmsParser createParser(XtextTokenStream stream) {
		return new InternalEvmsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public EvmsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EvmsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
