/**
 * generated by Xtext 2.36.0
 */
package org.example.evms.evms;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Evenement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.evms.evms.Evenement#getName <em>Name</em>}</li>
 *   <li>{@link org.example.evms.evms.Evenement#getTitre <em>Titre</em>}</li>
 *   <li>{@link org.example.evms.evms.Evenement#getDescription <em>Description</em>}</li>
 *   <li>{@link org.example.evms.evms.Evenement#getDateDebut <em>Date Debut</em>}</li>
 *   <li>{@link org.example.evms.evms.Evenement#getDateFin <em>Date Fin</em>}</li>
 *   <li>{@link org.example.evms.evms.Evenement#getLieu <em>Lieu</em>}</li>
 *   <li>{@link org.example.evms.evms.Evenement#getCreateur <em>Createur</em>}</li>
 *   <li>{@link org.example.evms.evms.Evenement#getInscriptions <em>Inscriptions</em>}</li>
 *   <li>{@link org.example.evms.evms.Evenement#getNotifications <em>Notifications</em>}</li>
 * </ul>
 *
 * @see org.example.evms.evms.EvmsPackage#getEvenement()
 * @model
 * @generated
 */
public interface Evenement extends RootElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.example.evms.evms.EvmsPackage#getEvenement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Evenement#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Titre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Titre</em>' attribute.
   * @see #setTitre(String)
   * @see org.example.evms.evms.EvmsPackage#getEvenement_Titre()
   * @model
   * @generated
   */
  String getTitre();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Evenement#getTitre <em>Titre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Titre</em>' attribute.
   * @see #getTitre()
   * @generated
   */
  void setTitre(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see org.example.evms.evms.EvmsPackage#getEvenement_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Evenement#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Date Debut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Date Debut</em>' attribute.
   * @see #setDateDebut(String)
   * @see org.example.evms.evms.EvmsPackage#getEvenement_DateDebut()
   * @model
   * @generated
   */
  String getDateDebut();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Evenement#getDateDebut <em>Date Debut</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Date Debut</em>' attribute.
   * @see #getDateDebut()
   * @generated
   */
  void setDateDebut(String value);

  /**
   * Returns the value of the '<em><b>Date Fin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Date Fin</em>' attribute.
   * @see #setDateFin(String)
   * @see org.example.evms.evms.EvmsPackage#getEvenement_DateFin()
   * @model
   * @generated
   */
  String getDateFin();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Evenement#getDateFin <em>Date Fin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Date Fin</em>' attribute.
   * @see #getDateFin()
   * @generated
   */
  void setDateFin(String value);

  /**
   * Returns the value of the '<em><b>Lieu</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lieu</em>' reference.
   * @see #setLieu(Lieu)
   * @see org.example.evms.evms.EvmsPackage#getEvenement_Lieu()
   * @model
   * @generated
   */
  Lieu getLieu();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Evenement#getLieu <em>Lieu</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lieu</em>' reference.
   * @see #getLieu()
   * @generated
   */
  void setLieu(Lieu value);

  /**
   * Returns the value of the '<em><b>Createur</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Createur</em>' reference.
   * @see #setCreateur(Utilisateur)
   * @see org.example.evms.evms.EvmsPackage#getEvenement_Createur()
   * @model
   * @generated
   */
  Utilisateur getCreateur();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Evenement#getCreateur <em>Createur</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Createur</em>' reference.
   * @see #getCreateur()
   * @generated
   */
  void setCreateur(Utilisateur value);

  /**
   * Returns the value of the '<em><b>Inscriptions</b></em>' containment reference list.
   * The list contents are of type {@link org.example.evms.evms.Inscription}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inscriptions</em>' containment reference list.
   * @see org.example.evms.evms.EvmsPackage#getEvenement_Inscriptions()
   * @model containment="true"
   * @generated
   */
  EList<Inscription> getInscriptions();

  /**
   * Returns the value of the '<em><b>Notifications</b></em>' containment reference list.
   * The list contents are of type {@link org.example.evms.evms.Notification}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Notifications</em>' containment reference list.
   * @see org.example.evms.evms.EvmsPackage#getEvenement_Notifications()
   * @model containment="true"
   * @generated
   */
  EList<Notification> getNotifications();

} // Evenement
