/**
 * generated by Xtext 2.36.0
 */
package org.example.evms.evms;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.example.evms.evms.EvmsFactory
 * @model kind="package"
 * @generated
 */
public interface EvmsPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "evms";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.example.org/eVMS";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "evms";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  EvmsPackage eINSTANCE = org.example.evms.evms.impl.EvmsPackageImpl.init();

  /**
   * The meta object id for the '{@link org.example.evms.evms.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.evms.evms.impl.ModelImpl
   * @see org.example.evms.evms.impl.EvmsPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.example.evms.evms.impl.RootElementImpl <em>Root Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.evms.evms.impl.RootElementImpl
   * @see org.example.evms.evms.impl.EvmsPackageImpl#getRootElement()
   * @generated
   */
  int ROOT_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Root Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.example.evms.evms.impl.EvenementImpl <em>Evenement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.evms.evms.impl.EvenementImpl
   * @see org.example.evms.evms.impl.EvmsPackageImpl#getEvenement()
   * @generated
   */
  int EVENEMENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENEMENT__NAME = ROOT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Titre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENEMENT__TITRE = ROOT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENEMENT__DESCRIPTION = ROOT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Date Debut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENEMENT__DATE_DEBUT = ROOT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Date Fin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENEMENT__DATE_FIN = ROOT_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Lieu</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENEMENT__LIEU = ROOT_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Createur</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENEMENT__CREATEUR = ROOT_ELEMENT_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Inscriptions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENEMENT__INSCRIPTIONS = ROOT_ELEMENT_FEATURE_COUNT + 7;

  /**
   * The feature id for the '<em><b>Notifications</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENEMENT__NOTIFICATIONS = ROOT_ELEMENT_FEATURE_COUNT + 8;

  /**
   * The number of structural features of the '<em>Evenement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENEMENT_FEATURE_COUNT = ROOT_ELEMENT_FEATURE_COUNT + 9;

  /**
   * The meta object id for the '{@link org.example.evms.evms.impl.LieuImpl <em>Lieu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.evms.evms.impl.LieuImpl
   * @see org.example.evms.evms.impl.EvmsPackageImpl#getLieu()
   * @generated
   */
  int LIEU = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__NAME = ROOT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__NOM = ROOT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Adresse</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__ADRESSE = ROOT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Capacite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__CAPACITE = ROOT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Lieu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_FEATURE_COUNT = ROOT_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.example.evms.evms.impl.UtilisateurImpl <em>Utilisateur</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.evms.evms.impl.UtilisateurImpl
   * @see org.example.evms.evms.impl.EvmsPackageImpl#getUtilisateur()
   * @generated
   */
  int UTILISATEUR = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UTILISATEUR__NAME = ROOT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UTILISATEUR__NOM = ROOT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UTILISATEUR__EMAIL = ROOT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Role</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UTILISATEUR__ROLE = ROOT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Mot De Passe</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UTILISATEUR__MOT_DE_PASSE = ROOT_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Utilisateur</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UTILISATEUR_FEATURE_COUNT = ROOT_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.example.evms.evms.impl.InscriptionImpl <em>Inscription</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.evms.evms.impl.InscriptionImpl
   * @see org.example.evms.evms.impl.EvmsPackageImpl#getInscription()
   * @generated
   */
  int INSCRIPTION = 5;

  /**
   * The feature id for the '<em><b>Utilisateur</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSCRIPTION__UTILISATEUR = ROOT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Evenement</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSCRIPTION__EVENEMENT = ROOT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Inscription</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSCRIPTION_FEATURE_COUNT = ROOT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.example.evms.evms.impl.NotificationImpl <em>Notification</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.evms.evms.impl.NotificationImpl
   * @see org.example.evms.evms.impl.EvmsPackageImpl#getNotification()
   * @generated
   */
  int NOTIFICATION = 6;

  /**
   * The feature id for the '<em><b>Message</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTIFICATION__MESSAGE = ROOT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Destinataire</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTIFICATION__DESTINATAIRE = ROOT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Evenement</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTIFICATION__EVENEMENT = ROOT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Notification</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTIFICATION_FEATURE_COUNT = ROOT_ELEMENT_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link org.example.evms.evms.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.example.evms.evms.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.evms.evms.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.example.evms.evms.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link org.example.evms.evms.RootElement <em>Root Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Root Element</em>'.
   * @see org.example.evms.evms.RootElement
   * @generated
   */
  EClass getRootElement();

  /**
   * Returns the meta object for class '{@link org.example.evms.evms.Evenement <em>Evenement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Evenement</em>'.
   * @see org.example.evms.evms.Evenement
   * @generated
   */
  EClass getEvenement();

  /**
   * Returns the meta object for the attribute '{@link org.example.evms.evms.Evenement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.example.evms.evms.Evenement#getName()
   * @see #getEvenement()
   * @generated
   */
  EAttribute getEvenement_Name();

  /**
   * Returns the meta object for the attribute '{@link org.example.evms.evms.Evenement#getTitre <em>Titre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Titre</em>'.
   * @see org.example.evms.evms.Evenement#getTitre()
   * @see #getEvenement()
   * @generated
   */
  EAttribute getEvenement_Titre();

  /**
   * Returns the meta object for the attribute '{@link org.example.evms.evms.Evenement#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.example.evms.evms.Evenement#getDescription()
   * @see #getEvenement()
   * @generated
   */
  EAttribute getEvenement_Description();

  /**
   * Returns the meta object for the attribute '{@link org.example.evms.evms.Evenement#getDateDebut <em>Date Debut</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Date Debut</em>'.
   * @see org.example.evms.evms.Evenement#getDateDebut()
   * @see #getEvenement()
   * @generated
   */
  EAttribute getEvenement_DateDebut();

  /**
   * Returns the meta object for the attribute '{@link org.example.evms.evms.Evenement#getDateFin <em>Date Fin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Date Fin</em>'.
   * @see org.example.evms.evms.Evenement#getDateFin()
   * @see #getEvenement()
   * @generated
   */
  EAttribute getEvenement_DateFin();

  /**
   * Returns the meta object for the reference '{@link org.example.evms.evms.Evenement#getLieu <em>Lieu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Lieu</em>'.
   * @see org.example.evms.evms.Evenement#getLieu()
   * @see #getEvenement()
   * @generated
   */
  EReference getEvenement_Lieu();

  /**
   * Returns the meta object for the reference '{@link org.example.evms.evms.Evenement#getCreateur <em>Createur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Createur</em>'.
   * @see org.example.evms.evms.Evenement#getCreateur()
   * @see #getEvenement()
   * @generated
   */
  EReference getEvenement_Createur();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.evms.evms.Evenement#getInscriptions <em>Inscriptions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Inscriptions</em>'.
   * @see org.example.evms.evms.Evenement#getInscriptions()
   * @see #getEvenement()
   * @generated
   */
  EReference getEvenement_Inscriptions();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.evms.evms.Evenement#getNotifications <em>Notifications</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Notifications</em>'.
   * @see org.example.evms.evms.Evenement#getNotifications()
   * @see #getEvenement()
   * @generated
   */
  EReference getEvenement_Notifications();

  /**
   * Returns the meta object for class '{@link org.example.evms.evms.Lieu <em>Lieu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lieu</em>'.
   * @see org.example.evms.evms.Lieu
   * @generated
   */
  EClass getLieu();

  /**
   * Returns the meta object for the attribute '{@link org.example.evms.evms.Lieu#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.example.evms.evms.Lieu#getName()
   * @see #getLieu()
   * @generated
   */
  EAttribute getLieu_Name();

  /**
   * Returns the meta object for the attribute '{@link org.example.evms.evms.Lieu#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see org.example.evms.evms.Lieu#getNom()
   * @see #getLieu()
   * @generated
   */
  EAttribute getLieu_Nom();

  /**
   * Returns the meta object for the attribute '{@link org.example.evms.evms.Lieu#getAdresse <em>Adresse</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Adresse</em>'.
   * @see org.example.evms.evms.Lieu#getAdresse()
   * @see #getLieu()
   * @generated
   */
  EAttribute getLieu_Adresse();

  /**
   * Returns the meta object for the attribute '{@link org.example.evms.evms.Lieu#getCapacite <em>Capacite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Capacite</em>'.
   * @see org.example.evms.evms.Lieu#getCapacite()
   * @see #getLieu()
   * @generated
   */
  EAttribute getLieu_Capacite();

  /**
   * Returns the meta object for class '{@link org.example.evms.evms.Utilisateur <em>Utilisateur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Utilisateur</em>'.
   * @see org.example.evms.evms.Utilisateur
   * @generated
   */
  EClass getUtilisateur();

  /**
   * Returns the meta object for the attribute '{@link org.example.evms.evms.Utilisateur#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.example.evms.evms.Utilisateur#getName()
   * @see #getUtilisateur()
   * @generated
   */
  EAttribute getUtilisateur_Name();

  /**
   * Returns the meta object for the attribute '{@link org.example.evms.evms.Utilisateur#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see org.example.evms.evms.Utilisateur#getNom()
   * @see #getUtilisateur()
   * @generated
   */
  EAttribute getUtilisateur_Nom();

  /**
   * Returns the meta object for the attribute '{@link org.example.evms.evms.Utilisateur#getEmail <em>Email</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Email</em>'.
   * @see org.example.evms.evms.Utilisateur#getEmail()
   * @see #getUtilisateur()
   * @generated
   */
  EAttribute getUtilisateur_Email();

  /**
   * Returns the meta object for the attribute '{@link org.example.evms.evms.Utilisateur#getRole <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Role</em>'.
   * @see org.example.evms.evms.Utilisateur#getRole()
   * @see #getUtilisateur()
   * @generated
   */
  EAttribute getUtilisateur_Role();

  /**
   * Returns the meta object for the attribute '{@link org.example.evms.evms.Utilisateur#getMotDePasse <em>Mot De Passe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mot De Passe</em>'.
   * @see org.example.evms.evms.Utilisateur#getMotDePasse()
   * @see #getUtilisateur()
   * @generated
   */
  EAttribute getUtilisateur_MotDePasse();

  /**
   * Returns the meta object for class '{@link org.example.evms.evms.Inscription <em>Inscription</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inscription</em>'.
   * @see org.example.evms.evms.Inscription
   * @generated
   */
  EClass getInscription();

  /**
   * Returns the meta object for the reference '{@link org.example.evms.evms.Inscription#getUtilisateur <em>Utilisateur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Utilisateur</em>'.
   * @see org.example.evms.evms.Inscription#getUtilisateur()
   * @see #getInscription()
   * @generated
   */
  EReference getInscription_Utilisateur();

  /**
   * Returns the meta object for the reference '{@link org.example.evms.evms.Inscription#getEvenement <em>Evenement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Evenement</em>'.
   * @see org.example.evms.evms.Inscription#getEvenement()
   * @see #getInscription()
   * @generated
   */
  EReference getInscription_Evenement();

  /**
   * Returns the meta object for class '{@link org.example.evms.evms.Notification <em>Notification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Notification</em>'.
   * @see org.example.evms.evms.Notification
   * @generated
   */
  EClass getNotification();

  /**
   * Returns the meta object for the attribute '{@link org.example.evms.evms.Notification#getMessage <em>Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Message</em>'.
   * @see org.example.evms.evms.Notification#getMessage()
   * @see #getNotification()
   * @generated
   */
  EAttribute getNotification_Message();

  /**
   * Returns the meta object for the reference '{@link org.example.evms.evms.Notification#getDestinataire <em>Destinataire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Destinataire</em>'.
   * @see org.example.evms.evms.Notification#getDestinataire()
   * @see #getNotification()
   * @generated
   */
  EReference getNotification_Destinataire();

  /**
   * Returns the meta object for the reference '{@link org.example.evms.evms.Notification#getEvenement <em>Evenement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Evenement</em>'.
   * @see org.example.evms.evms.Notification#getEvenement()
   * @see #getNotification()
   * @generated
   */
  EReference getNotification_Evenement();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  EvmsFactory getEvmsFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.example.evms.evms.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.evms.evms.impl.ModelImpl
     * @see org.example.evms.evms.impl.EvmsPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link org.example.evms.evms.impl.RootElementImpl <em>Root Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.evms.evms.impl.RootElementImpl
     * @see org.example.evms.evms.impl.EvmsPackageImpl#getRootElement()
     * @generated
     */
    EClass ROOT_ELEMENT = eINSTANCE.getRootElement();

    /**
     * The meta object literal for the '{@link org.example.evms.evms.impl.EvenementImpl <em>Evenement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.evms.evms.impl.EvenementImpl
     * @see org.example.evms.evms.impl.EvmsPackageImpl#getEvenement()
     * @generated
     */
    EClass EVENEMENT = eINSTANCE.getEvenement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENEMENT__NAME = eINSTANCE.getEvenement_Name();

    /**
     * The meta object literal for the '<em><b>Titre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENEMENT__TITRE = eINSTANCE.getEvenement_Titre();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENEMENT__DESCRIPTION = eINSTANCE.getEvenement_Description();

    /**
     * The meta object literal for the '<em><b>Date Debut</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENEMENT__DATE_DEBUT = eINSTANCE.getEvenement_DateDebut();

    /**
     * The meta object literal for the '<em><b>Date Fin</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENEMENT__DATE_FIN = eINSTANCE.getEvenement_DateFin();

    /**
     * The meta object literal for the '<em><b>Lieu</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENEMENT__LIEU = eINSTANCE.getEvenement_Lieu();

    /**
     * The meta object literal for the '<em><b>Createur</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENEMENT__CREATEUR = eINSTANCE.getEvenement_Createur();

    /**
     * The meta object literal for the '<em><b>Inscriptions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENEMENT__INSCRIPTIONS = eINSTANCE.getEvenement_Inscriptions();

    /**
     * The meta object literal for the '<em><b>Notifications</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENEMENT__NOTIFICATIONS = eINSTANCE.getEvenement_Notifications();

    /**
     * The meta object literal for the '{@link org.example.evms.evms.impl.LieuImpl <em>Lieu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.evms.evms.impl.LieuImpl
     * @see org.example.evms.evms.impl.EvmsPackageImpl#getLieu()
     * @generated
     */
    EClass LIEU = eINSTANCE.getLieu();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIEU__NAME = eINSTANCE.getLieu_Name();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIEU__NOM = eINSTANCE.getLieu_Nom();

    /**
     * The meta object literal for the '<em><b>Adresse</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIEU__ADRESSE = eINSTANCE.getLieu_Adresse();

    /**
     * The meta object literal for the '<em><b>Capacite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIEU__CAPACITE = eINSTANCE.getLieu_Capacite();

    /**
     * The meta object literal for the '{@link org.example.evms.evms.impl.UtilisateurImpl <em>Utilisateur</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.evms.evms.impl.UtilisateurImpl
     * @see org.example.evms.evms.impl.EvmsPackageImpl#getUtilisateur()
     * @generated
     */
    EClass UTILISATEUR = eINSTANCE.getUtilisateur();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UTILISATEUR__NAME = eINSTANCE.getUtilisateur_Name();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UTILISATEUR__NOM = eINSTANCE.getUtilisateur_Nom();

    /**
     * The meta object literal for the '<em><b>Email</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UTILISATEUR__EMAIL = eINSTANCE.getUtilisateur_Email();

    /**
     * The meta object literal for the '<em><b>Role</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UTILISATEUR__ROLE = eINSTANCE.getUtilisateur_Role();

    /**
     * The meta object literal for the '<em><b>Mot De Passe</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UTILISATEUR__MOT_DE_PASSE = eINSTANCE.getUtilisateur_MotDePasse();

    /**
     * The meta object literal for the '{@link org.example.evms.evms.impl.InscriptionImpl <em>Inscription</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.evms.evms.impl.InscriptionImpl
     * @see org.example.evms.evms.impl.EvmsPackageImpl#getInscription()
     * @generated
     */
    EClass INSCRIPTION = eINSTANCE.getInscription();

    /**
     * The meta object literal for the '<em><b>Utilisateur</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSCRIPTION__UTILISATEUR = eINSTANCE.getInscription_Utilisateur();

    /**
     * The meta object literal for the '<em><b>Evenement</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSCRIPTION__EVENEMENT = eINSTANCE.getInscription_Evenement();

    /**
     * The meta object literal for the '{@link org.example.evms.evms.impl.NotificationImpl <em>Notification</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.evms.evms.impl.NotificationImpl
     * @see org.example.evms.evms.impl.EvmsPackageImpl#getNotification()
     * @generated
     */
    EClass NOTIFICATION = eINSTANCE.getNotification();

    /**
     * The meta object literal for the '<em><b>Message</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NOTIFICATION__MESSAGE = eINSTANCE.getNotification_Message();

    /**
     * The meta object literal for the '<em><b>Destinataire</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOTIFICATION__DESTINATAIRE = eINSTANCE.getNotification_Destinataire();

    /**
     * The meta object literal for the '<em><b>Evenement</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOTIFICATION__EVENEMENT = eINSTANCE.getNotification_Evenement();

  }

} //EvmsPackage
