/**
 * generated by Xtext 2.36.0
 */
package org.example.evms.evms;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.example.evms.evms.EvmsPackage
 * @generated
 */
public interface EvmsFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  EvmsFactory eINSTANCE = org.example.evms.evms.impl.EvmsFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Root Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Root Element</em>'.
   * @generated
   */
  RootElement createRootElement();

  /**
   * Returns a new object of class '<em>Evenement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Evenement</em>'.
   * @generated
   */
  Evenement createEvenement();

  /**
   * Returns a new object of class '<em>Lieu</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Lieu</em>'.
   * @generated
   */
  Lieu createLieu();

  /**
   * Returns a new object of class '<em>Utilisateur</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Utilisateur</em>'.
   * @generated
   */
  Utilisateur createUtilisateur();

  /**
   * Returns a new object of class '<em>Inscription</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Inscription</em>'.
   * @generated
   */
  Inscription createInscription();

  /**
   * Returns a new object of class '<em>Notification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Notification</em>'.
   * @generated
   */
  Notification createNotification();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  EvmsPackage getEvmsPackage();

} //EvmsFactory
