/**
 * generated by Xtext 2.36.0
 */
package org.example.evms.evms;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Inscription</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.evms.evms.Inscription#getUtilisateur <em>Utilisateur</em>}</li>
 *   <li>{@link org.example.evms.evms.Inscription#getEvenement <em>Evenement</em>}</li>
 * </ul>
 *
 * @see org.example.evms.evms.EvmsPackage#getInscription()
 * @model
 * @generated
 */
public interface Inscription extends RootElement
{
  /**
   * Returns the value of the '<em><b>Utilisateur</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Utilisateur</em>' reference.
   * @see #setUtilisateur(Utilisateur)
   * @see org.example.evms.evms.EvmsPackage#getInscription_Utilisateur()
   * @model
   * @generated
   */
  Utilisateur getUtilisateur();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Inscription#getUtilisateur <em>Utilisateur</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Utilisateur</em>' reference.
   * @see #getUtilisateur()
   * @generated
   */
  void setUtilisateur(Utilisateur value);

  /**
   * Returns the value of the '<em><b>Evenement</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Evenement</em>' reference.
   * @see #setEvenement(Evenement)
   * @see org.example.evms.evms.EvmsPackage#getInscription_Evenement()
   * @model
   * @generated
   */
  Evenement getEvenement();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Inscription#getEvenement <em>Evenement</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Evenement</em>' reference.
   * @see #getEvenement()
   * @generated
   */
  void setEvenement(Evenement value);

} // Inscription
