/**
 * generated by Xtext 2.36.0
 */
package org.example.evms.evms;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lieu</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.evms.evms.Lieu#getName <em>Name</em>}</li>
 *   <li>{@link org.example.evms.evms.Lieu#getNom <em>Nom</em>}</li>
 *   <li>{@link org.example.evms.evms.Lieu#getAdresse <em>Adresse</em>}</li>
 *   <li>{@link org.example.evms.evms.Lieu#getCapacite <em>Capacite</em>}</li>
 * </ul>
 *
 * @see org.example.evms.evms.EvmsPackage#getLieu()
 * @model
 * @generated
 */
public interface Lieu extends RootElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.example.evms.evms.EvmsPackage#getLieu_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Lieu#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nom</em>' attribute.
   * @see #setNom(String)
   * @see org.example.evms.evms.EvmsPackage#getLieu_Nom()
   * @model
   * @generated
   */
  String getNom();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Lieu#getNom <em>Nom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nom</em>' attribute.
   * @see #getNom()
   * @generated
   */
  void setNom(String value);

  /**
   * Returns the value of the '<em><b>Adresse</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Adresse</em>' attribute.
   * @see #setAdresse(String)
   * @see org.example.evms.evms.EvmsPackage#getLieu_Adresse()
   * @model
   * @generated
   */
  String getAdresse();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Lieu#getAdresse <em>Adresse</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Adresse</em>' attribute.
   * @see #getAdresse()
   * @generated
   */
  void setAdresse(String value);

  /**
   * Returns the value of the '<em><b>Capacite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Capacite</em>' attribute.
   * @see #setCapacite(int)
   * @see org.example.evms.evms.EvmsPackage#getLieu_Capacite()
   * @model
   * @generated
   */
  int getCapacite();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Lieu#getCapacite <em>Capacite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Capacite</em>' attribute.
   * @see #getCapacite()
   * @generated
   */
  void setCapacite(int value);

} // Lieu
