/**
 * generated by Xtext 2.36.0
 */
package org.example.evms.evms;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Notification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.evms.evms.Notification#getMessage <em>Message</em>}</li>
 *   <li>{@link org.example.evms.evms.Notification#getDestinataire <em>Destinataire</em>}</li>
 *   <li>{@link org.example.evms.evms.Notification#getEvenement <em>Evenement</em>}</li>
 * </ul>
 *
 * @see org.example.evms.evms.EvmsPackage#getNotification()
 * @model
 * @generated
 */
public interface Notification extends RootElement
{
  /**
   * Returns the value of the '<em><b>Message</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message</em>' attribute.
   * @see #setMessage(String)
   * @see org.example.evms.evms.EvmsPackage#getNotification_Message()
   * @model
   * @generated
   */
  String getMessage();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Notification#getMessage <em>Message</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message</em>' attribute.
   * @see #getMessage()
   * @generated
   */
  void setMessage(String value);

  /**
   * Returns the value of the '<em><b>Destinataire</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Destinataire</em>' reference.
   * @see #setDestinataire(Utilisateur)
   * @see org.example.evms.evms.EvmsPackage#getNotification_Destinataire()
   * @model
   * @generated
   */
  Utilisateur getDestinataire();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Notification#getDestinataire <em>Destinataire</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Destinataire</em>' reference.
   * @see #getDestinataire()
   * @generated
   */
  void setDestinataire(Utilisateur value);

  /**
   * Returns the value of the '<em><b>Evenement</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Evenement</em>' reference.
   * @see #setEvenement(Evenement)
   * @see org.example.evms.evms.EvmsPackage#getNotification_Evenement()
   * @model
   * @generated
   */
  Evenement getEvenement();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Notification#getEvenement <em>Evenement</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Evenement</em>' reference.
   * @see #getEvenement()
   * @generated
   */
  void setEvenement(Evenement value);

} // Notification
