/**
 * generated by Xtext 2.36.0
 */
package org.example.evms.evms;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Root Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.example.evms.evms.EvmsPackage#getRootElement()
 * @model
 * @generated
 */
public interface RootElement extends EObject
{
} // RootElement
