/**
 * generated by Xtext 2.36.0
 */
package org.example.evms.evms;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Utilisateur</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.evms.evms.Utilisateur#getName <em>Name</em>}</li>
 *   <li>{@link org.example.evms.evms.Utilisateur#getNom <em>Nom</em>}</li>
 *   <li>{@link org.example.evms.evms.Utilisateur#getEmail <em>Email</em>}</li>
 *   <li>{@link org.example.evms.evms.Utilisateur#getRole <em>Role</em>}</li>
 *   <li>{@link org.example.evms.evms.Utilisateur#getMotDePasse <em>Mot De Passe</em>}</li>
 * </ul>
 *
 * @see org.example.evms.evms.EvmsPackage#getUtilisateur()
 * @model
 * @generated
 */
public interface Utilisateur extends RootElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.example.evms.evms.EvmsPackage#getUtilisateur_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Utilisateur#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nom</em>' attribute.
   * @see #setNom(String)
   * @see org.example.evms.evms.EvmsPackage#getUtilisateur_Nom()
   * @model
   * @generated
   */
  String getNom();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Utilisateur#getNom <em>Nom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nom</em>' attribute.
   * @see #getNom()
   * @generated
   */
  void setNom(String value);

  /**
   * Returns the value of the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Email</em>' attribute.
   * @see #setEmail(String)
   * @see org.example.evms.evms.EvmsPackage#getUtilisateur_Email()
   * @model
   * @generated
   */
  String getEmail();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Utilisateur#getEmail <em>Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Email</em>' attribute.
   * @see #getEmail()
   * @generated
   */
  void setEmail(String value);

  /**
   * Returns the value of the '<em><b>Role</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Role</em>' attribute.
   * @see #setRole(String)
   * @see org.example.evms.evms.EvmsPackage#getUtilisateur_Role()
   * @model
   * @generated
   */
  String getRole();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Utilisateur#getRole <em>Role</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Role</em>' attribute.
   * @see #getRole()
   * @generated
   */
  void setRole(String value);

  /**
   * Returns the value of the '<em><b>Mot De Passe</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mot De Passe</em>' attribute.
   * @see #setMotDePasse(String)
   * @see org.example.evms.evms.EvmsPackage#getUtilisateur_MotDePasse()
   * @model
   * @generated
   */
  String getMotDePasse();

  /**
   * Sets the value of the '{@link org.example.evms.evms.Utilisateur#getMotDePasse <em>Mot De Passe</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mot De Passe</em>' attribute.
   * @see #getMotDePasse()
   * @generated
   */
  void setMotDePasse(String value);

} // Utilisateur
