/**
 * generated by Xtext 2.36.0
 */
package org.example.evms.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;
import org.example.evms.evms.Evenement;
import org.example.evms.evms.Inscription;
import org.example.evms.evms.Model;
import org.example.evms.evms.Notification;
import org.example.evms.evms.RootElement;
import org.example.evms.services.EvmsGrammarAccess;

@SuppressWarnings("all")
public class EvmsFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private EvmsGrammarAccess _evmsGrammarAccess;

  protected void _format(final Model model, @Extension final IFormattableDocument document) {
    EList<RootElement> _elements = model.getElements();
    for (final RootElement rootElement : _elements) {
      document.<RootElement>format(rootElement);
    }
  }

  protected void _format(final Evenement evenement, @Extension final IFormattableDocument document) {
    EList<Inscription> _inscriptions = evenement.getInscriptions();
    for (final Inscription inscription : _inscriptions) {
      document.<Inscription>format(inscription);
    }
    EList<Notification> _notifications = evenement.getNotifications();
    for (final Notification notification : _notifications) {
      document.<Notification>format(notification);
    }
  }

  @XbaseGenerated
  public void format(final Object evenement, final IFormattableDocument document) {
    if (evenement instanceof XtextResource) {
      _format((XtextResource)evenement, document);
      return;
    } else if (evenement instanceof Evenement) {
      _format((Evenement)evenement, document);
      return;
    } else if (evenement instanceof Model) {
      _format((Model)evenement, document);
      return;
    } else if (evenement instanceof EObject) {
      _format((EObject)evenement, document);
      return;
    } else if (evenement == null) {
      _format((Void)null, document);
      return;
    } else if (evenement != null) {
      _format(evenement, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(evenement, document).toString());
    }
  }
}
