/*
 * generated by Xtext 2.36.0
 */
package org.example.evms;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EvmsStandaloneSetup extends EvmsStandaloneSetupGenerated {

	public static void doSetup() {
		new EvmsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
